[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -ra -q

# opcional pero muy útil
markers =
    slow: tests lentos
    integration: tests de integración
pythonpath=src
